# -*- coding: utf-8 -*-
"""AlgoMind.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TxXa85wNruwoc3Rle9s3zsocBxh53vBS
"""

algorithms = [
    {
        "name": "Merge Sort",
        "type": "sorting",
        "time": "O(n log n)",
        "space": "O(n)"
    },
    {
        "name": "Quick Sort",
        "type": "sorting",
        "time": "O(n log n)",
        "space": "O(log n)"
    },
    {
        "name": "Dijkstra",
        "type": "graph",
        "time": "O(n log n)",
        "space": "O(n)"
    },
    #P (Polynomial)
    {
        "name": "Merge Sort",
        "type": "sorting",
        "class": "P",
        "time": "O(n log n)",
        "space": "O(n)"
    },

    #Graph / Informed
    {
        "name": "Dijkstra",
        "type": "graph",
        "class": "P",
        "time": "O(n log n)",
        "space": "O(n)"
    },
    {
        "name": "A* Search",
        "type": "graph",
        "class": "P",
        "time": "O(n log n)",
        "space": "O(n)"
    },

    #NP (Exact but expensive)
    {
        "name": "Backtracking",
        "type": "combinatorial",
        "class": "NP",
        "time": "O(2^n)",
        "space": "O(n)"
    },

    #NP-Complete
    {
        "name": "Subset Sum (DP)",
        "type": "dp",
        "class": "NP-Complete",
        "time": "O(n * sum)",
        "space": "O(n * sum)"
    },

    #NP-Hard
    {
        "name": "Genetic Algorithm",
        "type": "optimization",
        "class": "NP-Hard",
        "time": "O(k * n)",
        "space": "O(n)"
    },
    {
        "name": "Simulated Annealing",
        "type": "optimization",
        "class": "NP-Hard",
        "time": "O(k)",
        "space": "O(1)"
    }
]

import heapq

# -------- Sorting --------
def merge_sort(arr):
    if len(arr) <= 1:
        return arr

    mid = len(arr) // 2
    left = merge_sort(arr[:mid])
    right = merge_sort(arr[mid:])

    return merge(left, right)

def merge(left, right):
    result = []
    i = j = 0

    while i < len(left) and j < len(right):
        if left[i] < right[j]:
            result.append(left[i])
            i += 1
        else:
            result.append(right[j])
            j += 1

    result.extend(left[i:])
    result.extend(right[j:])
    return result


def quick_sort(arr):
    if len(arr) <= 1:
        return arr

    pivot = arr[len(arr)//2]
    left = [x for x in arr if x < pivot]
    mid = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]

    return quick_sort(left) + mid + quick_sort(right)


# Graph
def dijkstra(graph, start=0):
    dist = {node: float('inf') for node in graph}
    dist[start] = 0
    pq = [(0, start)]

    while pq:
        d, node = heapq.heappop(pq)

        for neighbor, weight in graph[node]:
            if dist[neighbor] > d + weight:
                dist[neighbor] = d + weight
                heapq.heappush(pq, (dist[neighbor], neighbor))

    return dist

import time
import tracemalloc

def measure(func, data):
    tracemalloc.start()

    start = time.perf_counter()
    func(data)
    end = time.perf_counter()

    current, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    return {
        "time": end - start,
        "memory": peak / 1024 / 1024  # MB
    }

def time_rank(t):
    order = {
        "O(1)": 1,
        "O(log n)": 2,
        "O(n)": 3,
        "O(n log n)": 4,
        "O(n^2)": 5
    }
    return order.get(t, 10)


def score(algo):
    return time_rank(algo["time"])

def generate_data(problem_type, n):
    if problem_type == "sorting":
        return [random.randint(1, 100000) for _ in range(n)]

    elif problem_type == "graph":
        graph = {i: [] for i in range(n)}
        for i in range(n):
            for _ in range(2):
                graph[i].append((random.randint(0, n-1), 1))
        return graph


def get_function(name):
    if name == "Merge Sort":
        return merge_sort
    elif name == "Quick Sort":
        return quick_sort
    elif name == "Dijkstra":
        return dijkstra


def select_algorithm(problem_type, n):
    candidates = [a for a in algorithms if a["type"] == problem_type]

    best = None
    best_score = float("inf")

    for algo in candidates:
        s = score(algo)

        func = get_function(algo["name"])
        data = generate_data(problem_type, min(n, 2000))

        perf = measure(func, data)

        # combine score + runtime
        final_score = s + perf["time"] * 10

        if final_score < best_score:
            best_score = final_score
            best = (algo, perf)

    return best
    def classify_problem(description):

      desc = description.lower()

    if "sort" in desc:
        return "sorting", "P"

    elif "shortest path" in desc:
        return "graph", "P"

    elif "subset" in desc:
        return "dp", "NP-Complete"

    elif "optimize" in desc or "maximize" in desc:
        return "optimization", "NP-Hard"

    elif "permutation" in desc:
        return "combinatorial", "NP"

    return "general", "P"

def classify_problem(desc):
    desc = desc.lower()

    if "sort" in desc:
        return "sorting", "P"

    elif "shortest path" in desc:
        return "graph", "P"

    elif "subset" in desc:
        return "dp", "NP-Complete"

    elif "optimize" in desc:
        return "optimization", "NP-Hard"

    return "general", "P"

import random
def get_function(name):
    return {
        "Merge Sort": merge_sort,
        "Quick Sort": quick_sort,
        "Dijkstra": dijkstra,

    }.get(name)


def generate_data(problem_type, n):
    if problem_type == "sorting":
        return [random.randint(1, 10000) for _ in range(n)]

    elif problem_type == "graph":
        g = {i: [] for i in range(n)}
        for i in range(n):
            for _ in range(2):
                g[i].append((random.randint(0, n-1), 1))
        return g

    return [random.randint(1, 100) for _ in range(n)]


def select_algorithm(desc, n):
    problem_type, complexity = classify_problem(desc)

    candidates = [a for a in algorithms if a["type"] == problem_type]

    best = None
    best_time = float("inf")

    for algo in candidates:
        func = get_function(algo["name"])
        data = generate_data(problem_type, min(n, 2000))

        try:
            t, mem = measure(func, data)

            if t < best_time:
                best_time = t
                best = (algo, t, mem)
        except:
            continue

    return best